[package]
name = "holochain-conductor-runtime-ffi"
version = "0.2.1"
edition = "2021"


[lib]
crate-type = ["cdylib", "staticlib"]
name = "holochain_conductor_runtime_ffi"

[dependencies]
holochain-conductor-runtime = { path = "../runtime" }
holochain-conductor-runtime-types-ffi = { path = "../runtime-types-ffi" }
holochain_conductor_api = { workspace = true }
holochain_types = { workspace = true }
log = { workspace = true }
android_logger = { workspace = true }
uniffi = { workspace = true, features = ["tokio"] }
thiserror = { workspace = true }
url2 = { workspace = true }
tokio = { workspace = true, features = ["full"] }
sodoken = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }
uuid = { workspace = true }
