name: Static Analysis
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust toolchain
        uses: mkroening/rust-toolchain-toml@main

      - uses: Swatinem/rust-cache@v2
        name: Enable Rust Caching
        with:
          cache-on-failure: true
      
      - name: Make Static
        run: CHK_SQL_FMT=1 make static
